target: ''
exp_name: 'DifferentEncoderDecoder/simulate_EncoderDecoder/Hela'
num: 15000
scale: '2pi'
# 0.6 # 0.1 # 0.05 # 0.01 # 0.005 # 0.001
dist: 0.01
dist2: 0.03
dist3: 0.05
dist4: 0.07
#128 #256 #512 #1024 #1920
image_height: 1920
image_width: 2560
core_radius: 6 #5
constraint: 'strong'

IsReal: true
NumOfDist: 4
# Hela,USAF
WhichData: "Hela"
fi: 2
isfi: False
before_resize:
  flag: False
  size: 256

after_resize:
  flag: False
  size: 1024

noise:
  flag: False
  mean: 0
  std: 0.01

device: 'cuda'
seed: 1
batch_size: 1
lr: 0.001
epochs: 3000

input_channel: 1

model:
  name: 'U_Net'
  filename: 'model'
  classname: 'U_Net'

loss:
  name: 'MSELoss'

loops: [10,100,1000,3000,10000,15000]

  # 'L1Loss'        
# # prop的默认参数
# dx = 2.2e-6
# dy = dx
# lam = 532e-9
